
  import 'dart:ui';

import 'package:flutter/material.dart';

final Map<String, Color> colorsMap = {
    'Red': Colors.red,
    'Green': Colors.green,
    'Blue': Colors.blue,
    'Black': Colors.black,
    'White': Colors.white,
    'Cyan': Colors.cyan,
    'Lime': Colors.lime,
    'Indigo': Colors.indigo,
    'Teal': Colors.teal,
    'Amber': Colors.amber,
    'Deep Orange': Colors.deepOrange,
    'Deep Purple': Colors.deepPurple,
    'Light Blue': Colors.lightBlue,
    'Light Green': Colors.lightGreen,
    'Blue Grey': Colors.blueGrey,
    'Yellow Accent': Colors.yellowAccent,
    'Pink Accent': Colors.pinkAccent,
    'Purple Accent': Colors.purpleAccent,
    'Orange Accent': Colors.orangeAccent,
    'Green Accent': Colors.greenAccent,
    'Blue Accent': Colors.blueAccent,
    'Red Accent': Colors.redAccent,
    'Cyan Accent': Colors.cyanAccent,
    'Lime Accent': Colors.limeAccent,
    'Teal Accent': Colors.tealAccent,
    'Amber Accent': Colors.amberAccent,
    'Deep Orange Accent': Colors.deepOrangeAccent,
    'Deep Purple Accent': Colors.deepPurpleAccent,
    'Light Blue Accent': Colors.lightBlueAccent,
    'Light Green Accent': Colors.lightGreenAccent,
    'Dark Red': Colors.red[900]!,
    'Light Red': Colors.red[100]!,
    'Dark Grey': Colors.grey[850]!,
    'Cream': Colors.orange[50]!,
    'Gold': const Color(0xFFFFD700),       
    'Silver': const Color(0xFFC0C0C0),     
    'Navy Blue': const Color(0xFF000080),  
    'Maroon': const Color(0xFF800000),     
    'Olive': const Color(0xFF808000),      
    'Coral': const Color(0xFFFF7F50),      
    'Hot Pink': const Color(0xFFFF69B4),   
    'Turquoise': const Color(0xFF40E0D0),  
    'Violet': const Color(0xFFEE82EE),     
    'Chocolate': const Color(0xFFD2691E),  
  };
